"""
scripts.seed_neo4j - apply the Neo4j schema + seed the static Nashik topology.

Usage:
    python -m scripts.seed_neo4j                         # apply schema + seed (live)
    python -m scripts.seed_neo4j --emit-cypher PATH      # write seed Cypher, no DB

The static topology (venues, zones, booths, landmarks, adjacency) is built from
scripts.seed_data so its UUIDs match the PostgreSQL seed exactly. Runtime nodes
(MissingReport / FoundReport / Person / Phone / ...) are NOT seeded here - they
are MERGEd on the fly by services.neo4j_client.

`--emit-cypher` regenerates graph/seed_nashik.cypher from seed_data without
needing a database or the neo4j driver, so the committed reference file can never
drift from the data module.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow `python scripts/seed_neo4j.py` (not just -m) by ensuring repo root on path.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.seed_data import (  # noqa: E402
    ADJACENCY,
    BOOTHS,
    LANDMARKS,
    ZONES,
    booth_id,
    zone_id,
)

_GRAPH_DIR = Path(__file__).resolve().parent.parent / "graph"


def _q(value: str) -> str:
    """Escape a string literal for embedding in Cypher (double single-quotes)."""
    return value.replace("'", "''")


def build_topology_statements() -> list[str]:
    """Return literal Cypher MERGE statements for the full static topology."""
    stmts: list[str] = []

    # Venues
    for venue in sorted({z["venue"] for z in ZONES}):
        stmts.append(f"MERGE (:Venue {{name: '{_q(venue)}'}});")

    # Zones (+ PART_OF venue)
    for z in ZONES:
        zid = str(zone_id(z["slug"]))
        stmts.append(
            f"MERGE (z:Zone {{id: '{zid}'}}) "
            f"SET z.name = '{_q(z['name'])}', z.venue = '{_q(z['venue'])}', "
            f"z.display_name_marathi = '{_q(z['display_name_marathi'])}', "
            f"z.color_code = '{_q(z['color_code'])}';"
        )
        stmts.append(
            f"MATCH (z:Zone {{id: '{zid}'}}), (v:Venue {{name: '{_q(z['venue'])}'}}) "
            f"MERGE (z)-[:PART_OF]->(v);"
        )

    # Landmarks (+ IN_ZONE)
    for lm in LANDMARKS:
        zid = str(zone_id(lm["zone_slug"]))
        stmts.append(
            f"MERGE (l:Landmark {{name: '{_q(lm['name'])}'}}) "
            f"WITH l MATCH (z:Zone {{id: '{zid}'}}) MERGE (l)-[:IN_ZONE]->(z);"
        )

    # Booths (+ IN_ZONE)
    for b in BOOTHS:
        bid = str(booth_id(b["slug"]))
        zid = str(zone_id(b["zone_slug"]))
        stmts.append(
            f"MERGE (b:Booth {{id: '{bid}'}}) "
            f"SET b.name = '{_q(b['name'])}' "
            f"WITH b MATCH (z:Zone {{id: '{zid}'}}) MERGE (b)-[:IN_ZONE]->(z);"
        )

    # Adjacency (bidirectional)
    for a_slug, b_slug in ADJACENCY:
        aid, bid = str(zone_id(a_slug)), str(zone_id(b_slug))
        stmts.append(
            f"MATCH (a:Zone {{id: '{aid}'}}), (b:Zone {{id: '{bid}'}}) "
            f"MERGE (a)-[:ADJACENT_TO]->(b) MERGE (b)-[:ADJACENT_TO]->(a);"
        )

    return stmts


def _schema_statements() -> list[str]:
    """Split graph/schema.cypher into individual statements (drop comments)."""
    raw = (_GRAPH_DIR / "schema.cypher").read_text(encoding="utf-8")
    out: list[str] = []
    for chunk in raw.split(";"):
        lines = [ln for ln in chunk.splitlines() if not ln.strip().startswith("//")]
        stmt = "\n".join(lines).strip()
        if stmt:
            out.append(stmt + ";")
    return out


def emit_cypher(path: Path) -> None:
    """Write the schema + topology as a single readable .cypher reference file."""
    header = (
        "// ───────────────────────────────────────────────────────────────────\n"
        "// GENERATED by scripts/seed_neo4j.py --emit-cypher - DO NOT EDIT BY HAND.\n"
        "// Edit scripts/seed_data.py and regenerate so PostgreSQL + Neo4j ids stay\n"
        "// aligned. Seeds the static Nashik/Trimbakeshwar topology (SoW §5.3).\n"
        "// ───────────────────────────────────────────────────────────────────\n\n"
        "// ── Constraints (from graph/schema.cypher) ──\n"
    )
    body = "\n".join(_schema_statements())
    body += "\n\n// ── Static topology ──\n"
    body += "\n".join(build_topology_statements())
    path.write_text(header + body + "\n", encoding="utf-8")
    print(f"wrote {path}")


def seed_live() -> None:
    """Connect to Neo4j and apply schema + topology. Idempotent (all MERGE)."""
    from neo4j import GraphDatabase  # imported lazily so --emit-cypher needs no driver

    from core.config import settings

    driver = GraphDatabase.driver(
        settings.NEO4J_URI, auth=(settings.NEO4J_USER, settings.NEO4J_PASSWORD)
    )
    try:
        with driver.session() as session:
            for stmt in _schema_statements():
                session.run(stmt)
            for stmt in build_topology_statements():
                session.run(stmt)
        print("Neo4j schema + topology seeded.")
    finally:
        driver.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed NANDI Neo4j graph.")
    parser.add_argument(
        "--emit-cypher",
        metavar="PATH",
        help="write the seed Cypher to PATH instead of connecting to a database",
    )
    args = parser.parse_args()

    if args.emit_cypher:
        emit_cypher(Path(args.emit_cypher))
    else:
        seed_live()


if __name__ == "__main__":
    main()
