"""initial NANDI schema

Creates the full PostgreSQL schema from SoW §5.1 plus the Member-1 face_embedding
extension columns, the pgvector HNSW indexes, the partial active-status index, and
the zone_case_summary materialized view.

Hand-written (not autogenerated) so the pgvector / PostGIS / HNSW DDL is exact.
Column names and types mirror db.models 1:1.

Revision ID: 0001
Revises:
Create Date: 2027-01-01
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Embedding dims - must equal settings.EMBEDDING_DIM / FACE_EMBEDDING_DIM and the
# Vector() columns in db.models. Hardcoded here so the migration is reproducible
# regardless of runtime env (SoW §12.5 - changing these means re-indexing).
TEXT_DIM = 1024  # multilingual-e5-large
FACE_DIM = 512   # InsightFace buffalo_l (ArcFace)


def upgrade() -> None:
    # ── Extensions ──────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # gen_random_uuid() is built-in on PG13+, but pgcrypto guarantees it anywhere.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ── zones ───────────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE zones (
            id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name                 TEXT NOT NULL,
            venue                TEXT NOT NULL,
            boundary             GEOMETRY(POLYGON, 4326),
            color_code           TEXT NOT NULL,
            display_name_marathi TEXT NOT NULL
        )
        """
    )

    # ── booths ──────────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE booths (
            id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            zone_id    UUID REFERENCES zones(id),
            name       TEXT NOT NULL,
            latitude   NUMERIC,
            longitude  NUMERIC,
            active     BOOLEAN DEFAULT true
        )
        """
    )

    # ── groups ──────────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE groups (
            id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            origin_city   TEXT,
            origin_state  TEXT,
            entry_point   TEXT,
            leader_phone  TEXT
        )
        """
    )

    # ── registrants ─────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE registrants (
            phone       TEXT PRIMARY KEY,
            zone_id     UUID REFERENCES zones(id),
            entry_time  TIMESTAMPTZ DEFAULT NOW(),
            name        TEXT,
            group_id    UUID REFERENCES groups(id)
        )
        """
    )

    # ── missing_reports ─────────────────────────────────────────────────────
    op.execute(
        f"""
        CREATE TABLE missing_reports (
            id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            filed_at              TIMESTAMPTZ DEFAULT NOW(),
            filed_by_phone        TEXT NOT NULL,
            subject_name          TEXT,
            subject_age           INT,
            subject_gender        VARCHAR(16),
            physical_description  TEXT NOT NULL,
            last_seen_zone_id     UUID REFERENCES zones(id),
            last_seen_landmark    TEXT,
            last_seen_time        TIMESTAMPTZ,
            photo_url             TEXT,
            language_spoken       TEXT,
            origin_city           TEXT,
            status                VARCHAR(16) DEFAULT 'active',
            matched_found_id      UUID,
            created_by_booth_id   UUID REFERENCES booths(id),
            embedding             vector({TEXT_DIM}),
            face_embedding        vector({FACE_DIM})
        )
        """
    )

    # ── found_reports ───────────────────────────────────────────────────────
    op.execute(
        f"""
        CREATE TABLE found_reports (
            id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            found_at              TIMESTAMPTZ DEFAULT NOW(),
            registered_at_booth   UUID REFERENCES booths(id),
            name_if_known         TEXT,
            approximate_age       INT,
            gender                VARCHAR(16),
            physical_description  TEXT NOT NULL,
            current_zone_id       UUID REFERENCES zones(id),
            photo_url             TEXT,
            language_spoken       TEXT,
            apparent_city_origin  TEXT,
            status                VARCHAR(16) DEFAULT 'unmatched',
            matched_report_id     UUID REFERENCES missing_reports(id),
            operator_notes        TEXT,
            embedding             vector({TEXT_DIM}),
            face_embedding        vector({FACE_DIM})
        )
        """
    )

    # ── case_events (audit trail) ───────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE case_events (
            id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            report_id    UUID NOT NULL,
            event_type   VARCHAR(32) NOT NULL,
            event_at     TIMESTAMPTZ DEFAULT NOW(),
            booth_id     UUID REFERENCES booths(id),
            operator_id  TEXT,
            metadata     JSONB
        )
        """
    )

    # ── btree indexes for time-ordering / audit lookups ─────────────────────
    op.execute("CREATE INDEX ix_missing_reports_filed_at ON missing_reports (filed_at)")
    op.execute("CREATE INDEX ix_found_reports_found_at   ON found_reports (found_at)")
    op.execute("CREATE INDEX ix_case_events_report_id    ON case_events (report_id)")
    op.execute("CREATE INDEX ix_case_events_event_type   ON case_events (event_type)")
    op.execute("CREATE INDEX ix_case_events_event_at     ON case_events (event_at)")

    # ── Partial index: only ever vector-scan ACTIVE missing reports ──────────
    # (SoW §12.8 #6 - never run a full-table vector scan.)
    op.execute(
        "CREATE INDEX ix_missing_reports_active ON missing_reports (status) "
        "WHERE status = 'active'"
    )

    # ── HNSW indexes for fast approximate nearest-neighbour search ───────────
    # PARTIAL on the active set (SoW §12.8 #6 - the vector index itself only ever
    # covers searchable rows, so a match query can NEVER full-table vector-scan).
    # Missing reports are searchable while 'active'; found reports while 'unmatched'.
    # The query's WHERE must include the same status predicate for the planner to
    # use these - services.matcher enforces that.
    op.execute(
        "CREATE INDEX ix_missing_reports_embedding_hnsw ON missing_reports "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64) "
        "WHERE status = 'active'"
    )
    op.execute(
        "CREATE INDEX ix_found_reports_embedding_hnsw ON found_reports "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64) "
        "WHERE status = 'unmatched'"
    )

    # ── zone_case_summary materialized view (dashboard) ─────────────────────
    op.execute(
        """
        CREATE MATERIALIZED VIEW zone_case_summary AS
        SELECT
            z.id    AS zone_id,
            z.name  AS zone_name,
            z.venue,
            COUNT(mr.id) FILTER (WHERE mr.status = 'active')    AS active_missing,
            COUNT(mr.id) FILTER (WHERE mr.status = 'matched')   AS matched,
            COUNT(mr.id) FILTER (WHERE mr.status = 'closed')    AS closed,
            COUNT(fr.id) FILTER (WHERE fr.status = 'unmatched') AS unmatched_found
        FROM zones z
        LEFT JOIN missing_reports mr ON mr.last_seen_zone_id = z.id
        LEFT JOIN found_reports   fr ON fr.current_zone_id   = z.id
        GROUP BY z.id, z.name, z.venue
        """
    )
    # Unique index → enables REFRESH MATERIALIZED VIEW CONCURRENTLY (non-blocking).
    op.execute(
        "CREATE UNIQUE INDEX ix_zone_case_summary_zone_id ON zone_case_summary (zone_id)"
    )


def downgrade() -> None:
    op.execute("DROP MATERIALIZED VIEW IF EXISTS zone_case_summary")
    op.execute("DROP TABLE IF EXISTS case_events")
    op.execute("DROP TABLE IF EXISTS found_reports")
    op.execute("DROP TABLE IF EXISTS missing_reports")
    op.execute("DROP TABLE IF EXISTS registrants")
    op.execute("DROP TABLE IF EXISTS groups")
    op.execute("DROP TABLE IF EXISTS booths")
    op.execute("DROP TABLE IF EXISTS zones")
    # Extensions are left installed - other databases on the cluster may use them.
